name: flutter_web_router
description: A basic flutter routing system for web.
version: 0.0.1
homepage: rob-b.co.uk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

